export const actionTypes = {

  MAIN_NAV_START_FETCHING: 'MAIN_NAV_START_FETCHING',
  MAIN_NAV_FETCHED: 'MAIN_NAV_FETCHED',
  MAIN_NAV_FETCH_ERROR: 'MAIN_NAV_FETCH_ERROR',

  BLOG_START_FETCHING: 'BLOG_START_FETCHING',
  BLOG_FETCHED: 'BLOG_FETCHED',
  BLOG_FETCH_ERROR: 'BLOG_FETCH_ERROR',

}